### ISSUE TITLE
resets the script in Windows

### ISSUE THREAD

**Issue by ARSadri** [uqfoundation/multiprocess#123]
Hi,

it may not be an issue of your package and I may be misunderstanding the whole concept, but the following code shows that (similar to multiprocessing itself) the script containing the Process() (and the one containing the main) reset when Process() is executed in Windows. This does not happen in Linux, and as far as I know, this is because windows does not allow proper spawning. This reduces the speed in Windows significantly compared to Linux because the files are reset and all imports must happen again. (A workaround of minimizing imports or putting them inside functions is not practical because I import non-professionally written packages that take serious amount of time to import)

```python
print('script')
from multiprocess import Process, Queue

def f(q):
    print('func')
    q.put('hello world')

if __name__ == '__main__':
    print('main')
    q = Queue()
    p = Process(target=f, args=[q])
    p.start()
    print (q.get())
    p.join()
```

**Comment by mmckerns** [comment]
@ARSadri: I'm not clear what you are either asking or requesting. Can you clarify? Also, if you would like me to try to reproduce some behavior you are seeing, then it would help if you give the versions of python, multiprocess, dill, and the OS details.  Yes, windows uses a `spawn` context instead of `fork` (as on linux) -- you can change the context on linux with `get_context`, and see if the timing is the same. Also, on windows, one should generally use `freeze_support` in `__main__`.

**Comment by ARSadri** [comment]
Hi,

The version of the Python is 3.10 and I upgraded mp and dill. The OS is MS Windows 10 Professional.

If you could kindly run the above code, you'll see that the text "script" will be written twice in Windows and once in Linux. This is because the entire python script is reset by using Process in Windows. That will slow the code down in this simple code and in more complex codes resets the entire program just because a module somewhere called Process. using freeze_support does not prevent the reset.

The question is if this is an issue that cannot be resolved in Windows as long as we are relying on mp? Do you have a solution?

Best regards,
Alireza

**Comment by mmckerns** [comment]
> I guess we are stuck with the spawn in Windows.

We are.  Thanks for reporting.
