### ISSUE TITLE
You are referring to examples in the docs, but there are none!

### ISSUE THREAD

**Issue by eabase** [uqfoundation/multiprocess#127]
[examples](https://multiprocess.readthedocs.io/en/latest/index.html?highlight=examples)

Where are they?

**Comment by mmckerns** [comment]
Aside from:
https://multiprocess.readthedocs.io/en/latest/index.html?highlight=examples#basic-usage

I assume you are referring to this:
```
See `multiprocess.examples` for a set of example scripts.
```

That appears to be an artifact. The examples used to be located inside the `multiprocess` module. They were moved one directory up... and thus aren't built with the code.  For python 3.7, they now live here: https://github.com/uqfoundation/multiprocess/tree/master/py3.7/examples.

Also, you can use `multiprocess` instead of `multiprocessing` in any examples of the latter.
