### ISSUE TITLE
Change class instance in place / update original object

### ISSUE THREAD

**Issue by tmssmith** [uqfoundation/multiprocess#151]
Hi,

I've seen a few discussions (https://stackoverflow.com/q/26805346, https://stackoverflow.com/q/26059764) where it's been suggested that multiprocess will be updated to allow updating objects in place, instead of returning the copy that is passed to the other process. Did anything come of this? I've had a look at the docs/issues but wasn't able to find anything relevant.

Specifically, I have a class A instance that references a number of class B instances. I want to update each class B instance in parallel while maintaining the original references in class A. Currently (as I now realise is expected), copies of the class B instances are made and updated, but the original instances referenced by class A are not.

Hopefully that's clear, let me know if you need more information.

Thanks a lot,
Tom

**Comment by mmckerns** [comment]
A minimal example in code would be the best.  However, given your explanation above, I'm not sure what you are describing makes sense to me.  When `multiprocess` launches a `map`, it serializes the object and sends it to the relevant process.  Then you'd need a change of the class definition in the local namespace... and then when the object is returned, it would ignore the original class and use the updated class.  That would mean you are looking for the class to deserialize by reference, now that the class has changed.  Is that correct?  `dill` provides an option to `ignore` the updated class definition on load, so that might be what you are looking for.

Here's an example of the expected behavior:
```
Python 3.8.17 (default, Jun 11 2023, 01:54:00) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> import multiprocess
>>> class Foo:
...   x = 1
...   def __init__(self, y):
...     self.y = y
...   def __call__(self, z):
...     return z + self.y + self.x
... 
>>> f = Foo(1)
>>> f(4)
6
>>> p = multiprocess.Pool(4)
>>> r = p.map_async(f, [1,2,3,4])
>>> f.__class__.x = 10
>>> r.get()
[3, 4, 5, 6]
>>> f(1)
12
```
However, if I think I was faster, or had added a delay, you might see that the results were updated to match the changed class.  The default setting for`dill.settings["ignore"]` is `False`, so it should see the updated class on load, I believe.  If you want it ignored, then change the setting to `True`.

Does this address your question?   Again, a code example would greatly help.

**Comment by tmssmith** [comment]
Thanks a lot for getting back to me. I think what you describe matches what I want to do, but just be clear here is a simple code example. Sorry for not providing one originally.

```
import multiprocess
import dill

class Test:
    def __init__(self, children, x):
        self.children = children
        self.x = x

    def update(self):
        # A long running method.
        self.x += 1

def modify(x):
    x.update()
    return x

if __name__ == "__main__":
    children = [Test(None, i) for i in range(5)]
    parent = Test(children, 0)

    with multiprocess.Pool() as p:
        test = p.map(modify, children)
    p.close()
    p.join()

    print([x.x for x in parent.children])
    # actual behaviour: [0, 1, 2, 3 , 4], desired behaviour: [1, 2, 3 , 4, 5]

    print([x.x for x in children])
    # actual behaviour: [0, 1, 2, 3 , 4], desired behaviour: [1, 2, 3 , 4, 5]

    print([x.x for x in test])
    # actual behaviour: [1, 2, 3 , 4, 5]
```

Based on my (limited) understanding of multiprocess and dill, this is all exactly as expected, but I would like to be able to achieve the desired behaviour indicated in the comments below the print functions.  Is this possible at all or fundamentally not?

I've experimented a little with dill.settings["byref"] and dill.settings["ignore"] but neither result in any obvious changes in output. dill.settings["byref"] results in a warning:

```
PicklingWarning: Cannot locate reference to <class '__main__.Test'>.
```

**Comment by mmckerns** [comment]
What you want to do is fundamentally possible, yes.  However, it's not what I thought you were asking me initially, which is why the settings didn't work for you.  You'll note that my example was modifying the class in `__main__`. Your example actually doesn't modify the class and/or class instance in `__main__` -- your function modifies a copy of the instance in a child process.  So, if you want to get a modified value of `x`, you need to do one of two things: (a) return the class instance from the child process and get `x` from the returned instances (you are doing this with `test`), or (b) use shared objects or shared memory.

See the examples of (b) here:
https://docs.python.org/3/library/multiprocessing.html#shared-ctypes-objects
https://docs.python.org/3/library/multiprocessing.shared_memory.html

**Comment by tmssmith** [comment]
I'm proceeding with approach (a) for now and will take a look at (b) in more detail in future. Thanks for your help on this and sorry for the delay in getting back to you. I'll close the issue.
