### ISSUE TITLE
`SystemError: initialization of _multiprocess raised unreported exception` in Python 3.5

### ISSUE THREAD

**Issue by mgserafi** [uqfoundation/multiprocess#32]
I tried running:
```
from multiprocess import Process, Queue
q = Queue()
```
which works fine in py2.7 but in py3.5 i get an error:
```
SystemError: initialization of _multiprocess raised unreported exception
```
This is different from #10 because the error occurs after importing (so importing seems to work fine). If I try to use the regular `queue` module, it looks like `multiprocess` tries to use the `pickle` method instead of `dill` to serialize.

**Comment by mmckerns** [comment]
@mgserafi: I can't reproduce the error you are seeing.  What is your OS and version of `multiprocess`?   If you are on Windows, it could be due to a lack of a C++ compiler.  I'm using the current development version of `multiprocess` and a Mac.

**Comment by mgserafi** [comment]
I'm on windows using multiprocess-0.70.5, but if i don't have a c++ compiler, how come it would work in py2.7 ?

**Comment by mmckerns** [comment]
So, on windows, you need a compiler.  I have several places where if `_multiprocess` doesn't import, then it falls back to `_multiprocessing`, so it can work without the compiler but it still uses `pickle` instead of `dill`.  I'm only catching `ImportError` and not `SystemError`, so I expect that in 2.7 it's throwing a `ImportError`.

I'll check on windows with 3.5 and see if I can reproduce your error.

There are free MS Windows C++ compilers available that are compatible with python 3.5, I'd suggest you go get one from MS if you don't have a compiler.

Alternately, you can wait an undisclosed amount of time... I just started building wheels, and I will release wheels for `multiprocess` soon (so you won't need a compiler). I'd suggest getting the compiler as it's a much more immediate solution.

If you try to send a `lambda` through a `map` and it fails, then I believe that will also confirm it's a compiler issue, since it would rely on `pickle`

**Comment by mgserafi** [comment]
I already had a C++ compiler when I was first attempting to create a queue.

Furthermore, I get the same `SystemError` when trying to create a `pool` in py3.5 so I wasn't able to test what you suggested. However, I was able to create one in py2.7 and I successfully sent a `lambda` function through a `map`, so I'm pretty sure its not an issue with the compiler. 
(I tried the creating the same `lambda` function in py3.5 on my Mac and did not get this error.)

I also tried running the example code in the py3.5 folder and I would get the same `SystemError` but would not get this error in py2.7.

**Comment by mmckerns** [comment]
@mgserafi: Hmmm.  I'm not seeing this error.  I tried the specified version of `multiprocess` on windows for both 2.7 and 3.5, and I'm not seeing any difference.  I ran the example code for both, and both worked for me.  If you want to see what my setup looks like for MS windows, it's here: https://github.com/mmckerns/tuthpc.  See toward the bottom of the page, in the section on installing on windows.

I don't know what's going on for you... 
Can you uninstall and reinstall `multiprocess` for python 3.5?
What happens if you do: `import _multiprocess`?

**Comment by mgserafi** [comment]
I was actually using py3.4 this entire time. 

It looks like its an issue with my vs c++ compiler, as I currently have versions compatible with py3.5 and py2.7. I tested it in a new setup with py3.5 and I'm not getting this issue.

Thanks for your help!
