### ISSUE TITLE
Can't pickle

### ISSUE THREAD

**Issue by dineshbvadhia** [uqfoundation/multiprocess#34]
I'm using the concurrent.futures ProcessPoolExecutor option.

Installed multiprocess to solve the "Can't pickle <class 'module'>: attribute lookup module on builtins failed" but it didn't work either.
 
The data is a static keras model which isn't pickable - see https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model.

I have enough memory for each process to hold a copy of the data model or for it to be placed in shared memory for all processes to access. But, how to solve the not pickable problem for a keras model?

**Comment by mmckerns** [comment]
I'm not sure what exactly you want here... it helps immensely if you can provide a minimal code sample that reproduces the error you are seeing.  Can you provide a minimal code sample?

In the abstract, I'd first look into `dill` to see if your `keras` model can be pickled.  If it can, then you can find success with using `multiprocess` -- and it's just a matter of working with some simple code example to demonstrate that.  So, first check pickling an instance with `dill`.

Second, the `keras` documentation seems to suggest using `hdf5`... so you may be interested in `klepto` which provides automated function caching and some other niceties, and supports object storage to HDF5.  But I don't know what exactly you want to do, since I haven't seen a code sample.

**Comment by dineshbvadhia** [comment]
Ah. The problem cannot be solved. The Issue can be closed. Thanks.
