### ISSUE TITLE
why are we passing class instance to method of already initialised class? 

### ISSUE THREAD

**Issue by PatxiofromAlphensign** [uqfoundation/multiprocess#79]
https://github.com/uqfoundation/multiprocess/blob/60d64c5b7073a1876c92d864f950384894ab97a7/py3.8/multiprocess/process.py#L121

`_Popen` should not take `self` as an argument

**Comment by mmckerns** [comment]
The reason `multiprocess` is... that `multiprocessing` is doing it: https://github.com/python/cpython/blob/693aeacf8851d1e9995073e27e50644a505dc49c/Lib/multiprocessing/process.py#L121

**Comment by PatxiofromAlphensign** [comment]
so does anyone know the reason behind it. It seems really odd. Maybe because `BaseProcess` is always meant to be used as a base class?

**Comment by mmckerns** [comment]
I don't.  I usually get familiar with parts of the code that I have to touch.  I've not had to touch that part of the code yet.

**Comment by mmckerns** [comment]
So... I'm not sure what the reason is, but it's still being done in `multiprocessing` in the most recent 3.8, 3.9, 3.10, etc.  As I'm not seeing any behavior issues that I can trace back to this, nor do I know if it's actually correct or not, I'm closing this issue.  I guess one could delete the passed `self`, and then run the test suite and examples, and see what happens.
