### ISSUE TITLE
readthedocs page is blank

### ISSUE THREAD

**Issue by johnny-a-hunter** [uqfoundation/multiprocess#98]
When I go to https://multiprocess.readthedocs.io/, I get a blank Read The Docs page (see image below). Apologies if I'm doing something stupid!
<img width="1194" alt="Screenshot 2022-02-08 at 14 26 53" src="https://user-images.githubusercontent.com/64610132/153007204-98d1f668-c80c-4273-bb10-caf967432c6e.png">

**Comment by mmckerns** [comment]
Hi, you aren't doing something stupid.  `readthedocs` fails to build (primarily due to the odd nature of the `multiprocess` build).  It needs to be fixed -- this is a known issue.  The workaround is that you can just use the `multiprocessing` docs, which are almost totally identical to the `multiprocess` docs.
