### ISSUE TITLE
Cannot run multiprocess from vscode jupyter code cells but runs fine when paste on jupyter notebook

### ISSUE THREAD

**Issue by Xiaoxiaonull** [uqfoundation/multiprocess#99]
Similar to this question below
https://github.com/microsoft/vscode-jupyter/issues/941
That problem was finally found to be a bug between ipython and multiprocessing
I replaced the multiprocessing in the code with multiprocess, and the code works fine in jupyter notebook, but the problem still occurs in vscode jupyter cell,I would like to ask if there is a solution to the problem related to vscode jupyter cell.

**Comment by mmckerns** [comment]
A jupiter cell does not live in the global notebook environment, jupyter fakes it pretty well though.  Without seeing your code, I can only expect that you are experiencing a pickling failure due to not being able to find certain object dependencies that are defined in another cell.  My experience is that if the code you want to use with `multiprocess` is fully contained within a single cell, it will work, while being split across multiple cells, it will likely not work.  This is a design issue in the jupyter notebook, and has nothing in particular to do with `multiprocess`.  You may have expereinced the behavior of a function in a cell not being able to find a dependency defined in another cell.

So, if this sounds like what you are experiencing, then let's close/void this issue.  If not, then please provide more information (i.e. a fully encapsulated example code, the traceback, version of python/multiprocess/jupyter/etc).

**Comment by Xiaoxiaonull** [comment]
Thank you very much for your answer, I'm sorry I didn't put out my code, because the problem I encountered is basically the same as the one in the URL I provided above, and the way to reproduce it is also basically the same.
After reading your answer I basically understand the cause of the problem, probably the underlying cause of the jupyter cell in vscode, so the solution to the problem is probably only to look forward to Microsoft's updates to vscode-related content.
